name: Count Lines of Code

on:
  push:
    branches:
      - master

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Count lines of code
        id: count
        run: |
          cpplines=$(find . -path ./lib -prune \
                  -name "*.cpp" -o -name "*.hpp" \
                  | xargs wc -l | awk '{total += $1} END {print total}')
          cmakelines=$(find . -path ./lib -prune \
                  -name "*.cmake" -o -name "CMakeLists.txt" \
                  | xargs wc -l | awk '{total += $1} END {print total}')
          echo "::set-output name=cpplines::$cpplines"
          echo "::set-output name=cmakelines::$cmakelines"

      - name: Update README.md
        run: |
          sed -i "s/Total lines of C++ code: [0-9]*/Total lines of C++ code: ${{ steps.count.outputs.cpplines }}/" README.md
          sed -i "s/Total lines of CMake code: [0-9]*/Total lines of CMake code: ${{ steps.count.outputs.cmakelines }}/" README.md
